#!/usr/bin/env bash

## this script is used to test the webhook locally.
## your webhook will get the and show the following message on console
## `{"severity":"INFO","message":"Uaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 的文字訊息: ping"}

## this script generated by ChatGPT

set -e

# 讀取 functions/.env
ENV_FILE="functions/.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "❌ 找不到 $ENV_FILE"
  exit 1
fi

# 將 .env 變成環境變數
export $(grep -v '^#' "$ENV_FILE" | xargs)

if [ -z "$LINE_CHANNEL_SECRET" ]; then
  echo "❌ LINE_CHANNEL_SECRET 未設定"
  exit 1
fi

# LINE webhook body
BODY='{
  "destination":"U1234567890abcdef",
  "events":[
    {
      "type":"message",
      "message":{
        "id":"12345678901234",
        "type":"text",
        "text":"ping"
      },
      "timestamp":1700000000000,
      "source":{
        "type":"user",
        "userId":"Uaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      },
      "replyToken":"dummyReplyToken1234567890"
    }
  ]
}'

# 計算 X-Line-Signature
SIGNATURE=$(echo -n "$BODY" | \
  openssl dgst -sha256 -hmac "$LINE_CHANNEL_SECRET" -binary | \
  openssl base64)

echo "▶ 使用的 LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET:0:6}******"
echo "▶ X-Line-Signature: $SIGNATURE"

# 發送 request
curl -X POST \
  http://127.0.0.1:5001/simple-firebase-linebot/asia-east1/trigger/webhook \
  -H "Content-Type: application/json" \
  -H "X-Line-Signature: $SIGNATURE" \
  -d "$BODY"
